// Raw markdown bodies for the raw (markdown) render lane.
//
// This module is imported ONLY by detail-route `load` functions (the pages that
// actually render a body), never by the homepage or section-index pages. That
// keeps the large reference-sheet text out of those pages' client bundles: a
// detail page code-splits and fetches just the one body it renders.
//
// SECURITY INVARIANT (carried from the reference registry): the public client
// bundle must equal the curated content set — no stray file's raw text may ride
// along just by living in the folder. That holds here because src/content is
// EXCLUSIVELY generated by scripts/sync-content.mjs (it is gitignored and rebuilt
// from the packet), and every file it writes is enumerated in the committed
// manifest that drives the registry. Detail loads additionally gate on the
// registry, so only a registered markdown entry's body is ever served.

const rawModules = import.meta.glob('/src/content/**/*.md', {
	query: '?raw',
	import: 'default',
}) as Record<string, () => Promise<string>>;

/** Load the raw markdown body for a manifest `out` path (e.g. `reference/common-patterns.md`). */
export async function loadRawBody(out: string): Promise<string | undefined> {
	const loader = rawModules[`/src/content/${out}`];
	return loader ? await loader() : undefined;
}

// Raw source for the `.svx` (mdsvex) lane — used ONLY for extracting a page's
// table of contents (see $lib/docs/markdown.ts `extractHeadings`), never for
// re-rendering: the actual svx render path stays the mdsvex-compiled `<Content>`
// import in the route component. Kept as its own glob so `rawModules` above
// stays exactly what its doc comment says it is (the markdown raw lane).
const rawSvxModules = import.meta.glob('/src/content/**/*.svx', {
	query: '?raw',
	import: 'default',
}) as Record<string, () => Promise<string>>;

/** Load the raw source text (markdown OR svx) for a manifest `out` path, for TOC extraction. */
export async function loadRawSource(out: string): Promise<string | undefined> {
	const path = `/src/content/${out}`;
	const loader = rawModules[path] ?? rawSvxModules[path];
	return loader ? await loader() : undefined;
}
