<script lang="ts">
	// Client search over the built site, powered by Pagefind
	// (https://pagefind.app). Pagefind's index + runtime JS are generated by
	// `pagefind --site build`, wired as the `postbuild` script (see
	// package.json) — they do NOT exist under `pnpm run dev`, so this
	// component degrades to a "search available in the built site" notice
	// until /pagefind/pagefind.js actually resolves (see `status`).
	//
	// The runtime is loaded lazily (only once the dialog is opened, not on
	// page load) via a `@vite-ignore` dynamic import: the file is a build
	// output, not a module Vite can see or bundle at dev/build time.
	import { Search, X, Loader2 } from '@lucide/svelte';
	import { Dialog } from '@skeletonlabs/skeleton-svelte';
	import { base } from '$app/paths';
	import { routeUrl } from '$lib/search/route-url.js';

	// Minimal slice of Pagefind's browser Search API — see
	// https://pagefind.app/docs/api/. Pagefind ships Node-side indexing types
	// only (node_modules/pagefind/types), not this browser module, so the
	// shapes used here are declared locally.
	interface PagefindSubResult {
		title: string;
		url: string;
		excerpt: string;
	}
	interface PagefindResultData {
		url: string;
		meta: { title?: string };
		excerpt: string;
		sub_results: PagefindSubResult[];
	}
	interface PagefindSearchResult {
		id: string;
		data: () => Promise<PagefindResultData>;
	}
	interface PagefindSearchResponse {
		results: PagefindSearchResult[];
	}
	interface PagefindModule {
		options: (config: { bundlePath?: string }) => Promise<void>;
		init: () => Promise<void>;
		debouncedSearch: (query: string) => Promise<PagefindSearchResponse | null>;
	}

	type Status = 'idle' | 'loading' | 'unavailable' | 'ready';

	let open = $state(false);
	let query = $state('');
	let status = $state<Status>('idle');
	let results = $state<PagefindResultData[]>([]);
	let pagefind: PagefindModule | null = null;
	let searchToken = 0;

	async function loadPagefind() {
		if (status === 'ready' || status === 'loading') return;
		status = 'loading';
		try {
			const bundlePath = `${base}/pagefind/`;
			// @vite-ignore — `pagefind.js` is written by the `postbuild` script
			// into the static build output; it is never a Vite module graph
			// entry, so a static import would fail to resolve in both dev and
			// this project's own build.
			const mod = (await import(/* @vite-ignore */ `${bundlePath}pagefind.js`)) as PagefindModule;
			await mod.options({ bundlePath });
			await mod.init();
			pagefind = mod;
			status = 'ready';
		} catch {
			// Expected under `pnpm run dev` (no index yet) and on any host that
			// hasn't run the postbuild indexing step.
			status = 'unavailable';
		}
	}

	function handleOpenChange(details: { open: boolean }) {
		open = details.open;
		if (details.open) void loadPagefind();
	}

	async function runSearch(term: string) {
		if (!pagefind || status !== 'ready') return;
		const trimmed = term.trim();
		if (trimmed.length < 2) {
			results = [];
			return;
		}
		const token = ++searchToken;
		const response = await pagefind.debouncedSearch(trimmed);
		if (response === null || token !== searchToken) return; // superseded by a newer keystroke
		results = await Promise.all(response.results.map((r) => r.data()));
	}

	$effect(() => {
		void runSearch(query);
	});

	function closeAndReset() {
		open = false;
		query = '';
		results = [];
	}
</script>

<Dialog {open} onOpenChange={handleOpenChange} closeOnInteractOutside closeOnEscape preventScroll>
	<Dialog.Trigger class="hover:bg-surface-200-800 rounded-sm p-2 transition-colors" aria-label="Search the site">
		<Search class="h-5 w-5" />
	</Dialog.Trigger>
	<Dialog.Backdrop class="fixed inset-0 z-40 bg-black/40" />
	<Dialog.Positioner class="fixed inset-0 z-50 flex items-start justify-center px-4 pt-[10vh]">
		<Dialog.Content class="bg-surface-50-950 border-surface-300-700 w-full max-w-lg rounded-lg border shadow-lg">
			<!-- Zag's dialog SSRs optimistic aria-labelledby/-describedby pointing at
			     the title/description ids, and only names the dialog when a title
			     element actually renders — so both must exist (visually hidden) or
			     the prerendered HTML carries dangling refs and the open dialog is a
			     nameless modal. Same Dialog.Title idiom as BindableDrawer. -->
			<Dialog.Title class="sr-only">Search the site</Dialog.Title>
			<Dialog.Description class="sr-only">
				Search the reference sheets, guide, and algorithm pages. Results update as you type.
			</Dialog.Description>
			<div class="border-surface-200-800 flex items-center gap-2 border-b px-4 py-3">
				<Search class="text-surface-500 h-4 w-4 shrink-0" aria-hidden="true" />
				<input
					type="search"
					class="w-full bg-transparent text-sm outline-none"
					placeholder="Search the reference sheets and guide…"
					aria-label="Search query"
					autocomplete="off"
					bind:value={query}
				/>
				<Dialog.CloseTrigger
					class="hover:bg-surface-200-800 shrink-0 rounded-sm p-1"
					aria-label="Close search"
					onclick={closeAndReset}
				>
					<X class="h-4 w-4" />
				</Dialog.CloseTrigger>
			</div>

			<div class="max-h-[60vh] overflow-y-auto p-2">
				{#if status === 'loading'}
					<p class="text-surface-500 flex items-center gap-2 px-3 py-4 text-sm">
						<Loader2 class="h-4 w-4 animate-spin" aria-hidden="true" /> Loading search index…
					</p>
				{:else if status === 'unavailable'}
					<p class="text-surface-500 px-3 py-4 text-sm">
						Search index not found — search is available in the built site (run <code class="font-mono"
							>pnpm run build</code
						> or visit the deployed site).
					</p>
				{:else if status === 'ready'}
					{#if query.trim().length < 2}
						<p class="text-surface-500 px-3 py-4 text-sm">Type at least 2 characters to search.</p>
					{:else if results.length === 0}
						<p class="text-surface-500 px-3 py-4 text-sm">No results for "{query}".</p>
					{:else}
						<ul class="space-y-1">
							{#each results as result (result.url)}
								<li>
									<a
										href={routeUrl(result.url)}
										class="hover:bg-surface-200-800 block rounded-sm px-3 py-2"
										onclick={closeAndReset}
									>
										<p class="text-sm font-semibold">{result.meta.title ?? routeUrl(result.url)}</p>
										<p class="text-surface-600-400 mt-0.5 line-clamp-2 text-xs leading-relaxed">
											<!-- eslint-disable-next-line svelte/no-at-html-tags -- Pagefind's own excerpt HTML (only <mark> tags), from our own indexed build output. -->
											{@html result.excerpt}
										</p>
									</a>
								</li>
							{/each}
						</ul>
					{/if}
				{/if}
			</div>
		</Dialog.Content>
	</Dialog.Positioner>
</Dialog>
